workspace(name = "validator")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_absl",
    sha256 = "03e9adad1a3836e447bafe6f83f2d7f36575df1726eed3a1f68b797fc63448f0",
    strip_prefix = "abseil-cpp-ef615a8f5dba98457a1e949d20f734b660633a9d",
    urls = ["https://github.com/abseil/abseil-cpp/archive/ef615a8f5dba98457a1e949d20f734b660633a9d.zip"],
)

http_archive(
    name = "com_google_googletest",
    sha256 = "df6cad4bf17df72d8d86306628701c01a45b9e001c7f2a3b28971c7e24b1035b",
    strip_prefix = "googletest-0320f517fd920866d918e564105d68fd4362040a",
    urls = ["https://github.com/google/googletest/archive/0320f517fd920866d918e564105d68fd4362040a.zip"],  # 2019-01-07
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "bf853c19f737447be9c9e98a4fd71284732561f5d1a7901fab55c20424b64da7",
    strip_prefix = "protobuf-3380463ff87873b1ed07b730c79d78477289d0cd",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/3380463ff87873b1ed07b730c79d78477289d0cd.zip"],
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

http_archive(
    name = "com_github_gflags_gflags",
    sha256 = "f30d68645f923364bed91301248e909a66c4dea77123eaa812b3c5b5f61a2239",
    strip_prefix = "gflags-986e8eed00ded8168ef4eaa6f925dc6be50b40fa",
    urls = ["https://github.com/gflags/gflags/archive/986e8eed00ded8168ef4eaa6f925dc6be50b40fa.zip"],
)

http_archive(
    name = "com_googlesource_code_re2",
    sha256 = "438d0b2a26519937f0c265783f98bf7477829a9068c15f88ec2bd270b7fffed1",
    strip_prefix = "re2-3e9622e0cd94ebba6e04d5c50b7af32029e330d8",
    urls = ["https://github.com/google/re2/archive/3e9622e0cd94ebba6e04d5c50b7af32029e330d8.zip"],
)

# rules_cc defines rules for generating C++ code from Protocol Buffers.
http_archive(
    name = "rules_cc",
    sha256 = "8cd53b3563a3f66daa1f06f97b78a35600986a547bb27bebcafb8b1f8f54efb0",
    strip_prefix = "rules_cc-8bb0eb5c5ccd96b91753bb112096bb6993d16d13",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/8bb0eb5c5ccd96b91753bb112096bb6993d16d13.zip"],
)
load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")
rules_cc_dependencies()

# rules_proto defines abstract rules for building Protocol Buffers.
http_archive(
    name = "rules_proto",
    sha256 = "fb7f1959d2d2bf4d7a1f4f29d650845a9a2303b7879c6792320ba8244910ab01",
    strip_prefix = "rules_proto-3212323502e21b819ac4fbdd455cb227ad0f6394",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/3212323502e21b819ac4fbdd455cb227ad0f6394.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/3212323502e21b819ac4fbdd455cb227ad0f6394.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

http_archive(
    name = "emsdk",
    sha256 = "4490c54c7573ef7e0c4ee7115fe8d7b5a38ac58dbcce5b3797518284b99e4707",
    strip_prefix = "emsdk-3d86ccb4257de7ad551a23dc8a33d28e7f1372ef/bazel",
    url = "https://github.com/emscripten-core/emsdk/archive/3d86ccb4257de7ad551a23dc8a33d28e7f1372ef.tar.gz",
)

load("@emsdk//:deps.bzl", emsdk_deps = "deps")
emsdk_deps()

load("@emsdk//:emscripten_deps.bzl", emsdk_emscripten_deps = "emscripten_deps")
emsdk_emscripten_deps(emscripten_version = "2.0.31")

http_archive(
    name = "com_google_javascript_closure_library",
    sha256 = "b12c5967a47962191026b61200eab57b88165d001f6fe646e61da1d4ef54bfb5",
    strip_prefix = "closure-library-6e5c4ecc09ed21239905c668f5743287c1deb641",
    urls = ["https://github.com/google/closure-library/archive/6e5c4ecc09ed21239905c668f5743287c1deb641.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "c8256d901f2c5eb11514e3ebaab1cad319ddec898d0212f6bc82a462b6f38840",
    strip_prefix = "rules_closure-03e1d4111227f88402da409e2b69a4ada5953550",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/03e1d4111227f88402da409e2b69a4ada5953550.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/03e1d4111227f88402da409e2b69a4ada5953550.tar.gz",
    ],
)

load("@io_bazel_rules_closure//closure:repositories.bzl", "rules_closure_dependencies", "rules_closure_toolchains")
rules_closure_dependencies()
rules_closure_toolchains()

local_repository(
    name = "amphtml-extensions",
    path = "../extensions",
)
